FROM docker.io/microsoft/mssql-server-linux
USER root
RUN apt-get update
RUN apt-get install curl -y
RUN curl --silent https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl --silent https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
RUN ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev -y
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c 'source ~/.bashrc'
