###################################################################################
## Openshift                                                                     ##
## Author: https://github.com/Iakim                                              ##
## Simplicity is the ultimate degree of sophistication                           ##
###################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: mssql
type: Opaque
stringData:
  SA_PASSWORD: 1qaz@wsx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: iakim/mssql-liferay:latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 10 && /opt/mssql-tools/bin/sqlcmd -s 127.0.0.1 -Usa -P 1qaz@wsx -Q 'EXIT(CREATE DATABASE liferay713cega4;)' && /opt/mssql-tools/bin/sqlcmd -s 127.0.0.1 -Usa -P 1qaz@wsx -Q 'EXIT(CREATE DATABASE liferay712cega3;)'"]
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
