###################################################################################
## Openshift                                                                     ##
## Author: https://github.com/Iakim                                              ##
## Simplicity is the ultimate degree of sophistication                           ##
###################################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: liferay-713cega4
spec:
  serviceName: "liferay-713cega4"
  replicas: 1
  selector:
    matchLabels:
      app: liferay-713cega4
  template:
    metadata:
      labels:
        app: liferay-713cega4
    spec:
      containers:
      - name: liferay-713cega4
        image: iakim/liferay:7.1.3CEGA4
        env:
          - name: JAVA_OPTS
            value: -server -Xmx4g -Xms4g -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -XX:SurvivorRatio=6 -Djboss.modules.policy-permissions=true -XX:+DoEscapeAnalysis -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=500 -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=2 -Duser.language=pt -Duser.region=BR -Duser.country=BR -Djava.awt.headless=true -XX:+UseCompressedOops -Duser.timezone=America/Sao_Paulo -Djboss.as.management.blocking.timeout=600
        ports:
        - containerPort: 8080
          name: liferay
        - containerPort: 9990
          name: jboss
        volumeMounts:
          - mountPath: /opt/jboss/deploy
            name: liferay-713cega4-deploy
          - mountPath: /opt/jboss/logs
            name: liferay-713cega4-logs
          - mountPath: /opt/jboss/osgi/modules
            name: liferay-713cega4-modules
          - mountPath: /opt/jboss/osgi/war
            name: liferay-713cega4-war
          - mountPath: /mnt/nfs/liferay/document_library
            name: liferay-713cega4-dl
      volumes:
      - name: liferay-713cega4-deploy
        persistentVolumeClaim:
          claimName: liferay-713cega4-deploy-pvc
      - name: liferay-713cega4-logs
        persistentVolumeClaim:
          claimName: liferay-713cega4-logs-pvc
      - name: liferay-713cega4-modules
        persistentVolumeClaim:
          claimName: liferay-713cega4-modules-pvc
      - name: liferay-713cega4-war
        persistentVolumeClaim:
          claimName: liferay-713cega4-war-pvc
      - name: liferay-713cega4-dl
        persistentVolumeClaim:
          claimName: liferay-713cega4-dl-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: liferay-713cega4
  labels:
    service: liferay-713cega4
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: liferay
  - port: 9990
    name: jboss
  selector:
    app: liferay-713cega4
---
apiVersion: v1
kind: Route
metadata:
  name: liferay-713cega4-route
spec:
  host: liferay-7-1-3-ce-ga4.seatecnologia.com.br
  path: ""
  to:
    kind: Service
    name: liferay-713cega4
  port:
    targetPort: liferay
