###################################################################################
## Openshift                                                                     ##
## Author: https://github.com/Iakim                                              ##
## Simplicity is the ultimate degree of sophistication                           ##
###################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-713cega4-deploy-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/liferay/tst/713cega4/deploy"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-713cega4-logs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/liferay/tst/713cega4/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-713cega4-modules-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/liferay/tst/713cega4/modules"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-713cega4-war-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/liferay/tst/713cega4/war"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-713cega4-dl-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/liferay/tst/713cega4/document_library"
